# Generated by Django 3.2.8 on 2021-11-07 16:22

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[authapp.models.validate_age], verbose_name='возраст'),
        ),
    ]
